-- Migration 002: role vocabulary, permission matrix, qualifications.
-- Generated from the live RoleConfig.jsx matrix. Role codes are the exact
-- strings the current app uses, so role_assignments migrate 1:1.

begin;

-- Roles ----------------------------------------------------------------
insert into role (code, display_name, scope, is_super, directory_only) values ('Auxiliarist', 'Auxiliarist', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('Division Commander', 'Division Commander', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-AS', 'FSO-AS', 'flotilla', false, true);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-CM', 'FSO-CM', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-CS', 'FSO-CS', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-DV', 'FSO-DV', 'flotilla', false, true);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-FN', 'FSO-FN', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-HR', 'FSO-HR', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-IS', 'FSO-IS', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-MA', 'FSO-MA', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-MS', 'FSO-MS', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-MT', 'FSO-MT', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-NS', 'FSO-NS', 'flotilla', false, true);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-OP', 'FSO-OP', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-PA', 'FSO-PA', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-PB', 'FSO-PB', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-PE', 'FSO-PE', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-PV', 'FSO-PV', 'flotilla', false, true);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-SC', 'FSO-SC', 'flotilla', false, true);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-SR', 'FSO-SR', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('FSO-VE', 'FSO-VE', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('Flotilla Commander', 'Flotilla Commander', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('Immediate Past Division Commander', 'Immediate Past Division Commander', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('Immediate Past Flotilla Commander', 'Immediate Past Flotilla Commander', 'flotilla', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-AS', 'SO-AS', 'division', false, true);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-CM', 'SO-CM', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-CS', 'SO-CS', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-DV', 'SO-DV', 'division', false, true);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-FN', 'SO-FN', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-HR', 'SO-HR', 'division', false, true);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-IS', 'SO-IS', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-MA', 'SO-MA', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-MS', 'SO-MS', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-MT', 'SO-MT', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-NS', 'SO-NS', 'division', false, true);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-OP', 'SO-OP', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-PA', 'SO-PA', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-PB', 'SO-PB', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-PE', 'SO-PE', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-PV', 'SO-PV', 'division', false, true);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-SC', 'SO-SC', 'division', false, true);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-SR', 'SO-SR', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('SO-VE', 'SO-VE', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('Super Admin', 'Super Admin', 'division', true, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('Vice Division Commander', 'Vice Division Commander', 'division', false, false);
insert into role (code, display_name, scope, is_super, directory_only) values ('Vice Flotilla Commander', 'Vice Flotilla Commander', 'flotilla', false, false);

-- Permissions ---------------------------------------------------------
insert into permission (entity, action) values ('bank_account', 'create');
insert into permission (entity, action) values ('bank_account', 'delete');
insert into permission (entity, action) values ('bank_account', 'edit');
insert into permission (entity, action) values ('bank_account', 'reconcile');
insert into permission (entity, action) values ('bank_account', 'view');
insert into permission (entity, action) values ('budget', 'approve');
insert into permission (entity, action) values ('budget', 'create');
insert into permission (entity, action) values ('budget', 'delete');
insert into permission (entity, action) values ('budget', 'edit');
insert into permission (entity, action) values ('budget', 'view');
insert into permission (entity, action) values ('committee', 'create');
insert into permission (entity, action) values ('committee', 'delete');
insert into permission (entity, action) values ('committee', 'edit');
insert into permission (entity, action) values ('committee', 'view');
insert into permission (entity, action) values ('division', 'create');
insert into permission (entity, action) values ('division', 'delete');
insert into permission (entity, action) values ('division', 'edit');
insert into permission (entity, action) values ('division', 'manage_settings');
insert into permission (entity, action) values ('division', 'view');
insert into permission (entity, action) values ('flotilla', 'create');
insert into permission (entity, action) values ('flotilla', 'delete');
insert into permission (entity, action) values ('flotilla', 'edit');
insert into permission (entity, action) values ('flotilla', 'manage_settings');
insert into permission (entity, action) values ('flotilla', 'view');
insert into permission (entity, action) values ('journal_entry', 'create');
insert into permission (entity, action) values ('journal_entry', 'delete');
insert into permission (entity, action) values ('journal_entry', 'edit');
insert into permission (entity, action) values ('journal_entry', 'view');
insert into permission (entity, action) values ('member', 'assign_roles');
insert into permission (entity, action) values ('member', 'create');
insert into permission (entity, action) values ('member', 'delete');
insert into permission (entity, action) values ('member', 'edit');
insert into permission (entity, action) values ('member', 'view');
insert into permission (entity, action) values ('payee_vendor', 'create');
insert into permission (entity, action) values ('payee_vendor', 'delete');
insert into permission (entity, action) values ('payee_vendor', 'edit');
insert into permission (entity, action) values ('payee_vendor', 'view');
insert into permission (entity, action) values ('report_schedule', 'create');
insert into permission (entity, action) values ('report_schedule', 'delete');
insert into permission (entity, action) values ('report_schedule', 'edit');
insert into permission (entity, action) values ('report_schedule', 'view');
insert into permission (entity, action) values ('transaction', 'approve');
insert into permission (entity, action) values ('transaction', 'audit');
insert into permission (entity, action) values ('transaction', 'create');
insert into permission (entity, action) values ('transaction', 'delete');
insert into permission (entity, action) values ('transaction', 'edit');
insert into permission (entity, action) values ('transaction', 'view');
insert into permission (entity, action) values ('vessel_exam', 'create');
insert into permission (entity, action) values ('vessel_exam', 'delete');
insert into permission (entity, action) values ('vessel_exam', 'edit');
insert into permission (entity, action) values ('vessel_exam', 'view');
insert into permission (entity, action) values ('volunteer_activity', 'create');
insert into permission (entity, action) values ('volunteer_activity', 'delete');
insert into permission (entity, action) values ('volunteer_activity', 'edit');
insert into permission (entity, action) values ('volunteer_activity', 'view');
insert into permission (entity, action) values ('volunteer_activity', 'view_all');

-- Role → permission ---------------------------------------------------
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'bank_account', 'create');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'bank_account', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'bank_account', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'bank_account', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'bank_account', 'delete');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'bank_account', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'bank_account', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'bank_account', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'bank_account', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'bank_account', 'reconcile');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'bank_account', 'reconcile');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'bank_account', 'reconcile');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'bank_account', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'bank_account', 'view');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'bank_account', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'bank_account', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'bank_account', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'bank_account', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'bank_account', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'budget', 'approve');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'budget', 'approve');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'budget', 'approve');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'budget', 'approve');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'budget', 'create');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'budget', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'budget', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'budget', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'budget', 'delete');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'budget', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'budget', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'budget', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'budget', 'edit');
insert into role_permission (role_code, entity, action) values ('Auxiliarist', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CM', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CS', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-HR', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-IS', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MA', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MS', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MT', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-OP', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PA', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PB', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PE', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-SR', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Division Commander', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Flotilla Commander', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CM', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CS', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-IS', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MA', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MS', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MT', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-OP', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PA', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PB', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PE', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-SR', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'budget', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'committee', 'create');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'committee', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'committee', 'create');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'committee', 'create');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'committee', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'committee', 'delete');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'committee', 'delete');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'committee', 'delete');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'committee', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'committee', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'committee', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'committee', 'edit');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'committee', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'committee', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'committee', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'committee', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'division', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'division', 'delete');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'division', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'division', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'division', 'edit');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'division', 'manage_settings');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'division', 'manage_settings');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'division', 'manage_settings');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'division', 'manage_settings');
insert into role_permission (role_code, entity, action) values ('Auxiliarist', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CM', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CS', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-HR', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-IS', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MA', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MS', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MT', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-OP', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PA', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PB', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PE', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-SR', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Division Commander', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Flotilla Commander', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CM', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CS', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-IS', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MA', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MS', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MT', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-OP', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PA', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PB', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PE', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-SR', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'division', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'flotilla', 'create');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'flotilla', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'flotilla', 'create');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'flotilla', 'create');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'flotilla', 'delete');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'flotilla', 'delete');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'flotilla', 'delete');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'flotilla', 'edit');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'flotilla', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'flotilla', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'flotilla', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'flotilla', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'flotilla', 'edit');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'flotilla', 'manage_settings');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'flotilla', 'manage_settings');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'flotilla', 'manage_settings');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'flotilla', 'manage_settings');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'flotilla', 'manage_settings');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'flotilla', 'manage_settings');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'flotilla', 'manage_settings');
insert into role_permission (role_code, entity, action) values ('Auxiliarist', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CM', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CS', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-HR', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-IS', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MA', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MS', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MT', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-OP', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PA', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PB', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PE', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-SR', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Division Commander', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Flotilla Commander', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CM', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CS', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-IS', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MA', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MS', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MT', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-OP', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PA', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PB', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PE', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-SR', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'flotilla', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'journal_entry', 'create');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'journal_entry', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'journal_entry', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'journal_entry', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'journal_entry', 'delete');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'journal_entry', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'journal_entry', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'journal_entry', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'journal_entry', 'edit');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'journal_entry', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'journal_entry', 'view');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'journal_entry', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'journal_entry', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'journal_entry', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'journal_entry', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'journal_entry', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'member', 'assign_roles');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'member', 'assign_roles');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'member', 'assign_roles');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'member', 'assign_roles');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'member', 'assign_roles');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'member', 'create');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'member', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'member', 'create');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'member', 'create');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'member', 'create');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'member', 'delete');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'member', 'delete');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'member', 'edit');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'member', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'member', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'member', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'member', 'edit');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'member', 'view');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'member', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'member', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'member', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'member', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'member', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'payee_vendor', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'payee_vendor', 'create');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'payee_vendor', 'create');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'payee_vendor', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'payee_vendor', 'create');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'payee_vendor', 'create');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'payee_vendor', 'create');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'payee_vendor', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'payee_vendor', 'delete');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'payee_vendor', 'delete');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'payee_vendor', 'delete');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'payee_vendor', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'payee_vendor', 'edit');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'payee_vendor', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'payee_vendor', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'payee_vendor', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'payee_vendor', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'payee_vendor', 'edit');
insert into role_permission (role_code, entity, action) values ('Auxiliarist', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CM', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CS', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-HR', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-IS', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MA', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MS', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MT', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-OP', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PA', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PB', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PE', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-SR', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Division Commander', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Flotilla Commander', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CM', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CS', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-IS', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MA', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MS', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MT', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-OP', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PA', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PB', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PE', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-SR', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'payee_vendor', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'report_schedule', 'create');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'report_schedule', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'report_schedule', 'create');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'report_schedule', 'create');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'report_schedule', 'delete');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'report_schedule', 'delete');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'report_schedule', 'delete');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'report_schedule', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'report_schedule', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'report_schedule', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'report_schedule', 'edit');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'report_schedule', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'report_schedule', 'view');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'report_schedule', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'report_schedule', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'report_schedule', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'report_schedule', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'report_schedule', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'transaction', 'approve');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'transaction', 'approve');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'transaction', 'approve');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'transaction', 'approve');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'transaction', 'approve');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'transaction', 'approve');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'transaction', 'audit');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'transaction', 'audit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'transaction', 'audit');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'transaction', 'audit');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'transaction', 'create');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'transaction', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'transaction', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'transaction', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'transaction', 'delete');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'transaction', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'transaction', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'transaction', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'transaction', 'edit');
insert into role_permission (role_code, entity, action) values ('Auxiliarist', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CM', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CS', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-HR', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-IS', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MA', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MS', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MT', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-OP', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PA', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PB', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PE', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-SR', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Division Commander', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Flotilla Commander', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CM', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CS', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-IS', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MA', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MS', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MT', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-OP', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PA', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PB', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PE', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-SR', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'transaction', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'vessel_exam', 'create');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'vessel_exam', 'create');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'vessel_exam', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'vessel_exam', 'create');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'vessel_exam', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'vessel_exam', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'vessel_exam', 'delete');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'vessel_exam', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'vessel_exam', 'edit');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'vessel_exam', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'vessel_exam', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'vessel_exam', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'vessel_exam', 'edit');
insert into role_permission (role_code, entity, action) values ('Auxiliarist', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CM', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CS', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-HR', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-IS', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MA', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MS', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MT', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-OP', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PA', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PB', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PE', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-SR', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Division Commander', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Flotilla Commander', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CM', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CS', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-IS', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MA', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MS', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MT', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-OP', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PA', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PB', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PE', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-SR', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'vessel_exam', 'view');
insert into role_permission (role_code, entity, action) values ('Auxiliarist', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-CM', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-CS', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-HR', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-IS', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-MA', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-MS', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-MT', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-OP', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-PA', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-PB', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-PE', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-SR', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-CM', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-CS', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-IS', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-MA', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-MS', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-MT', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-OP', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-PA', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-PB', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-PE', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-SR', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'volunteer_activity', 'create');
insert into role_permission (role_code, entity, action) values ('Auxiliarist', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-CM', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-CS', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-HR', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-IS', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-MA', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-MS', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-MT', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-OP', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-PA', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-PB', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-PE', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-SR', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-CM', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-CS', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-IS', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-MA', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-MS', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-MT', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-OP', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-PA', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-PB', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-PE', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-SR', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'volunteer_activity', 'delete');
insert into role_permission (role_code, entity, action) values ('Auxiliarist', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-CM', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-CS', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-HR', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-IS', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-MA', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-MS', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-MT', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-OP', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-PA', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-PB', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-PE', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-SR', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-CM', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-CS', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-IS', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-MA', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-MS', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-MT', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-OP', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-PA', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-PB', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-PE', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-SR', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'volunteer_activity', 'edit');
insert into role_permission (role_code, entity, action) values ('Auxiliarist', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CM', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-CS', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-FN', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-HR', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-IS', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MA', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MS', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-MT', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-OP', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PA', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PB', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-PE', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-SR', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('FSO-VE', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Division Commander', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('Immediate Past Flotilla Commander', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CM', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-CS', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-IS', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MA', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MS', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-MT', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-OP', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PA', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PB', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-PE', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-SR', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('SO-VE', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'volunteer_activity', 'view');
insert into role_permission (role_code, entity, action) values ('Division Commander', 'volunteer_activity', 'view_all');
insert into role_permission (role_code, entity, action) values ('Flotilla Commander', 'volunteer_activity', 'view_all');
insert into role_permission (role_code, entity, action) values ('SO-FN', 'volunteer_activity', 'view_all');
insert into role_permission (role_code, entity, action) values ('Super Admin', 'volunteer_activity', 'view_all');
insert into role_permission (role_code, entity, action) values ('Vice Division Commander', 'volunteer_activity', 'view_all');
insert into role_permission (role_code, entity, action) values ('Vice Flotilla Commander', 'volunteer_activity', 'view_all');

-- Qualifications (axis 2) ---------------------------------------------
-- VE gates vessel exams today. The others are seeded so currency can be
-- tracked; add permission gates only where the Division wants them.
insert into qualification (code, display_name, requires_currency, description) values
  ('VE',      'Vessel Examiner',        true,  'Conducts vessel safety checks'),
  ('IT',      'Instructor',             true,  'Delivers public education courses'),
  ('PV',      'Program Visitor',        true,  'Conducts marine dealer visits'),
  ('AUXOP',   'Operational Auxiliarist',false, 'Advanced qualification program'),
  ('COX',     'Coxswain',               true,  'Commands an operational facility'),
  ('CREW',    'Boat Crew',              true,  'Qualified operational crew');

commit;
